### PR TITLE
edited nba_scraper with testing function. edited Readme to explain ch…

### PR DESCRIPTION
**Pull request by kfoofw**
…romedriver requirement for testing

### CODE REVIEW

**Review by AndresPitta — COMMENTED** [review]
I see everything is good with this one

**Review by AndresPitta — APPROVED** [review]

**Comment by kfoofw** [comment]
I added docstrings to the test functions!

**Comment by kfoofw** [comment]
also note that test coverage was 100%! :)

**Comment by AndresPitta** [comment]
Ok, docstring noted

**Pull request merged**
